"""create sessions tables

Revision ID: 9f0efb80cbf6
Revises:
Create Date: 2026-06-15 22:20:55.554776

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9f0efb80cbf6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "session.started",
                "session.completed",
                "participant.message",
                "participant.vote",
                "participant.removed",
                "resolution.created",
                name="event_type",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_session_id"), "events", ["session_id"], unique=False)
    op.create_index(op.f("ix_events_type"), "events", ["type"], unique=False)
    op.create_table(
        "participants",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Enum("agent", "user", "system", name="participant_type"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "id", name="uq_participants_session_id_id"),
    )
    op.create_index(op.f("ix_participants_session_id"), "participants", ["session_id"], unique=False)
    op.create_table(
        "agent_participants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "participant_message_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_participant_message_events_sender_id"), "participant_message_events", ["sender_id"], unique=False
    )
    op.create_table(
        "participant_removed_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("removed_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["removed_id"],
            ["participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_participant_removed_events_removed_id"), "participant_removed_events", ["removed_id"], unique=False
    )
    op.create_table(
        "participant_vote_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("voter_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voter_id"],
            ["participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_participant_vote_events_target_id"), "participant_vote_events", ["target_id"], unique=False
    )
    op.create_index(op.f("ix_participant_vote_events_voter_id"), "participant_vote_events", ["voter_id"], unique=False)
    op.create_table(
        "resolution_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_participants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_participants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_participants")
    op.drop_table("system_participants")
    op.drop_table("resolution_events")
    op.drop_index(op.f("ix_participant_vote_events_voter_id"), table_name="participant_vote_events")
    op.drop_index(op.f("ix_participant_vote_events_target_id"), table_name="participant_vote_events")
    op.drop_table("participant_vote_events")
    op.drop_index(op.f("ix_participant_removed_events_removed_id"), table_name="participant_removed_events")
    op.drop_table("participant_removed_events")
    op.drop_index(op.f("ix_participant_message_events_sender_id"), table_name="participant_message_events")
    op.drop_table("participant_message_events")
    op.drop_table("agent_participants")
    op.drop_index(op.f("ix_participants_session_id"), table_name="participants")
    op.drop_table("participants")
    op.drop_index(op.f("ix_events_type"), table_name="events")
    op.drop_index(op.f("ix_events_session_id"), table_name="events")
    op.drop_table("events")
    op.drop_table("sessions")
    # ### end Alembic commands ###
